export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS'
export const LOAD_TODO_FAILURE = 'LOAD_TODO_FAILURE'

export const ADD_TODO = 'ADD_TODO'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE'

export const RESEND_TODO_SUCCESS = 'RESEND_TODO_SUCCESS'
export const RESEND_TODO_FAILURE = 'RESEND_TODO_FAILURE'

export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS'
export const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE'